# Generated by Django 4.1.3 on 2022-11-21 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SL', 'Shortlisted'), ('WL', 'Waitlisted'), ('AP', 'Approved'), ('RE', 'Rejected')], default='SL', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Scholarship Applications',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=2, null=True)),
                ('school', models.CharField(max_length=200, null=True)),
                ('study', models.CharField(max_length=200, null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employ_status', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('employer', models.CharField(max_length=255, null=True)),
                ('occupation', models.CharField(max_length=255, null=True)),
                ('experience', models.CharField(max_length=255, null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('partner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_admin', to='authentication.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('province', models.CharField(max_length=200, null=True)),
                ('municipality', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('social', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('details_privacy', models.CharField(max_length=200, null=True)),
                ('last_modified', models.DateField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('partner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('photo_verification', models.URLField()),
                ('status', models.BooleanField(null=True)),
                ('partner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.partner')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ScholarProfile',
        ),
        migrations.AddField(
            model_name='application',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='authentication.profile', verbose_name='Scholarium username'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='authentication.program', verbose_name='Program'),
        ),
    ]
