# Generated by Django 4.0.7 on 2022-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarprofile',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='scholarprofile',
            old_name='last_name',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
