# Generated by Django 4.0.7 on 2023-10-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_courseratoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseratoken',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
