# Generated by Django 4.1.3 on 2022-11-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_application_education_employment_partner_and_more'),
        ('authentication', '0002_rename_first_name_scholarprofile_fname_and_more'),
    ]

    operations = [
    ]
