# Generated by Django 4.1.3 on 2022-11-21 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_merge_20221121_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('emp_status', models.CharField(max_length=200, null=True)),
                ('industry', models.CharField(max_length=200, null=True)),
                ('employer', models.CharField(max_length=200, null=True)),
                ('occupation', models.CharField(max_length=200, null=True)),
                ('exp_level', models.CharField(max_length=200, null=True)),
                ('degree', models.CharField(max_length=200, null=True)),
                ('university', models.CharField(max_length=200, null=True)),
                ('field', models.CharField(max_length=200, null=True)),
                ('bio', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('province', models.CharField(max_length=200, null=True)),
                ('municipality', models.CharField(max_length=200, null=True)),
                ('social', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('details_privacy', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scholar Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='education',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='partneradmin',
            name='partner_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='program',
            name='partner_id',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='partner_id',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PartnerAdmin',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Scholar',
        ),
    ]
