EMPLOYMENT_STATUS = [
    'Full Time',
    'Part Time',
    'Self-Employed',
    'Homemaker',
    'Unemployed',
    'Retired',
    'Unable to Work',
]

INDUSTRY = [
    'Information Technology',
    'Others',
]

EXPERIENCE = [
    'Intern/Trainee',
    'Junior/Entry level (0-2 years experience)',
    'Mid-level (2+ years experience)',
    'Lead/Manager',
    'Senior Manager',
    'Executive Level',
    'Not Applicable',   
]

DEGREE = [
    'Less than high school diploma or equivalent',
    'Junior high diploma',
    'Senior high diploma',
    'Some units in college but no degree',
    'Associate degree',
    'Bachelor\u2019s Degree',
    "Master\u2019s degree",
    'Doctorate degree',
]

FIELD_OF_STUDY = [
    'Business',
    'Computer Science',
    'Engineering',
    'Mathematics and Statistics',
    'Physical Sciences',
    'Biological Sciences',
    'Social Sciences',
    'Health Professions',
    'Legal Professions',
    'Education',
    'Arts and Humanities',
    'Other',
    'Not Applicable',
]

# COUNTRY = [
#     'Afghanistan', 'Aland Islands', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia, Plurinational State of', 'Bonaire, Sint Eustatius and Saba', 'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island', 'Brazil', 'British Indian Ocean Territory', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo', 'Congo, The Democratic Republic of the', 'Cook Islands', 'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba', 'Curaçao', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'French Southern Territories', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heard Island and McDonald Islands', 'Holy See (Vatican City State)', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Republic of', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Democratic People's Republic of", 'Korea, Republic of', 'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao', 'Macedonia, Republic of', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia, Federated States of', 'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestinian Territory, Occupied', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Réunion', 'Romania', 'Russian Federation', 'Rwanda', 'Saint Barthélemy', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin (French part)', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia and the South Sandwich Islands', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'South Sudan', 'Svalbard and Jan Mayen', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Taiwan, Province of China', 'Tajikistan', 'Tanzania, United Republic of', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'United States Minor Outlying Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, Bolivarian Republic of', 'Viet Nam', 'Virgin Islands, British', 'Virgin Islands, U.S.', 'Wallis and Futuna', 'Yemen', 'Zambia', 'Zimbabwe'
# ]
COUNTRY = [
    'Philippines'
]

REGION = {
    'REGION1':'REGION I (ILOCOS REGION)',
    'REGION2':'REGION II (CAGAYAN VALLEY)',
    'REGION3':'REGION III (CENTRAL LUZON)',
    'REGION4A':'REGION IV-A (CALABARZON)',
    'REGION4B':'REGION IV-B (MIMAROPA)',
    'REGION5':'REGION V (BICOL REGION)',
    'REGION6':'REGION VI (WESTERN VISAYAS)',
    'REGION7':'REGION VII (CENTRAL VISAYAS)',
    'REGION8':'REGION VIII (EASTERN VISAYAS)',
    'REGION9':'REGION IX (ZAMBOANGA PENINSULA)',
    'REGION10':'REGION X (NORTHERN MINDANAO)',
    'REGION11':'REGION XI (DAVAO REGION)',
    'REGION12':'REGION XII (SOCCSKSARGEN)',
    'NCR':'NATIONAL CAPITAL REGION (NCR)',
    'CAR':'CORDILLERA ADMINISTRATIVE REGION (CAR)',
    'ARMM':'AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)',
    'REGION13':'REGION XIII (Caraga)',
}

# MUNICIPALITIES

MUNICIPALITIES = {
    'REGION1' : [
        'ADAMS',
        'AGNO',
        'AGOO',
        'AGUILAR',
        'ALCALA',
        'ALILEM',
        'ANDA',
        'ARINGAY',
        'ASINGAN',
        'BACARRA',
        'BACNOTAN',
        'BADOC',
        'BAGULIN',
        'BALAOAN',
        'BALUNGAO',
        'BANAYOYO',
        'BANGAR',
        'BANGUI',
        'BANI',
        'BANNA (ESPIRITU)',
        'BANTAY',
        'BASISTA',
        'BAUANG',
        'BAUTISTA',
        'BAYAMBANG',
        'BINALONAN',
        'BINMALEY',
        'BOLINAO',
        'BUGALLON',
        'BURGOS',
        'BURGOS',
        'BURGOS',
        'BURGOS',
        'CABA',
        'CABUGAO',
        'CALASIAO',
        'CAOAYAN',
        'CARASI',
        'CERVANTES',
        'CITY OF ALAMINOS',
        'CITY OF BATAC',
        'CITY OF CANDON',
        'CITY OF SAN FERNANDO (Capital)',
        'CITY OF URDANETA',
        'CITY OF VIGAN (Capital)',
        'CURRIMAO',
        'DAGUPAN CITY',
        'DASOL',
        'DINGRAS',
        'DUMALNEG',
        'GALIMUYOD',
        'GREGORIO DEL PILAR (CONCEPCION)',
        'INFANTA',
        'LABRADOR',
        'LAOAC',
        'LAOAG CITY (Capital)',
        'LIDLIDDA',
        'LINGAYEN (Capital)',
        'LUNA',
        'MABINI',
        'MAGSINGAL',
        'MALASIQUI',
        'MANAOAG',
        'MANGALDAN',
        'MANGATAREM',
        'MAPANDAN',
        'MARCOS',
        'NAGBUKEL',
        'NAGUILIAN',
        'NARVACAN',
        'NATIVIDAD',
        'NUEVA ERA',
        'PAGUDPUD',
        'PAOAY',
        'PASUQUIN',
        'PIDDIG',
        'PINILI',
        'POZORRUBIO',
        'PUGO',
        'QUIRINO (ANGKAKI)',
        'ROSALES',
        'ROSARIO',
        'SALCEDO (BAUGEN)',
        'SAN CARLOS CITY',
        'SAN EMILIO',
        'SAN ESTEBAN',
        'SAN FABIAN',
        'SAN GABRIEL',
        'SAN ILDEFONSO',
        'SAN JACINTO',
        'SAN JUAN',
        'SAN JUAN (LAPOG)',
        'SAN MANUEL',
        'SAN NICOLAS',
        'SAN NICOLAS',
        'SAN QUINTIN',
        'SAN VICENTE',
        'SANTA',
        'SANTA BARBARA',
        'SANTA CATALINA',
        'SANTA CRUZ',
        'SANTA LUCIA',
        'SANTA MARIA',
        'SANTA MARIA',
        'SANTIAGO',
        'SANTO DOMINGO',
        'SANTO TOMAS',
        'SANTO TOMAS',
        'SANTOL',
        'SARRAT',
        'SIGAY',
        'SINAIT',
        'SISON',
        'SOLSONA',
        'SUAL',
        'SUDIPEN',
        'SUGPON',
        'SUYO',
        'TAGUDIN',
        'TAYUG',
        'TUBAO',
        'UMINGAN',
        'URBIZTONDO',
        'VILLASIS',
        'VINTAR',
        ],
    
    'REGION2' : [
        'ABULUG',
        'AGLIPAY',
        'ALCALA',
        'ALFONSO CASTANEDA',
        'ALICIA',
        'ALLACAPAN',
        'AMBAGUIO',
        'AMULUNG',
        'ANGADANAN',
        'APARRI',
        'ARITAO',
        'AURORA',
        'BAGABAG',
        'BAGGAO',
        'BALLESTEROS',
        'BAMBANG',
        'BASCO (Capital)',
        'BAYOMBONG (Capital)',
        'BENITO SOLIVEN',
        'BUGUEY',
        'BURGOS',
        'CABAGAN',
        'CABARROGUIS (Capital)',
        'CABATUAN',
        'CALAYAN',
        'CAMALANIUGAN',
        'CITY OF CAUAYAN',
        'CITY OF SANTIAGO',
        'CLAVERIA',
        'CORDON',
        'DELFIN ALBANO (MAGSAYSAY)',
        'DIADI',
        'DIFFUN',
        'DINAPIGUE',
        'DIVILACAN',
        'DUPAX DEL NORTE',
        'DUPAX DEL SUR',
        'ECHAGUE',
        'ENRILE',
        'GAMU',
        'GATTARAN',
        'GONZAGA',
        'IGUIG',
        'ILAGAN CITY (Capital)',
        'ITBAYAT',
        'IVANA',
        'JONES',
        'KASIBU',
        'KAYAPA',
        'LAL-LO',
        'LASAM',
        'LUNA',
        'MACONACON',
        'MADDELA',
        'MAHATAO',
        'MALLIG',
        'NAGTIPUNAN',
        'NAGUILIAN',
        'PALANAN',
        'PAMPLONA',
        'PEÑABLANCA',
        'PIAT',
        'QUEZON',
        'QUEZON',
        'QUIRINO',
        'RAMON',
        'REINA MERCEDES',
        'RIZAL',
        'ROXAS',
        'SABTANG',
        'SAGUDAY',
        'SAN AGUSTIN',
        'SAN GUILLERMO',
        'SAN ISIDRO',
        'SAN MANUEL',
        'SAN MARIANO',
        'SAN MATEO',
        'SAN PABLO',
        'SANCHEZ-MIRA',
        'SANTA ANA',
        'SANTA FE',
        'SANTA MARIA',
        'SANTA PRAXEDES',
        'SANTA TERESITA',
        'SANTO NIÑO (FAIRE)',
        'SANTO TOMAS',
        'SOLANA',
        'SOLANO',
        'TUAO',
        'TUGUEGARAO CITY (Capital)',
        'TUMAUINI',
        'UYUGAN',
        'VILLAVERDE',
    ],
    
    'REGION3' : [
        'ABUCAY',
        'ALIAGA',
        'ANAO',
        'ANGAT',
        'ANGELES CITY',
        'APALIT',
        'ARAYAT',
        'BACOLOR',
        'BAGAC',
        'BALAGTAS (BIGAA)',
        'BALER (Capital)',
        'BALIUAG',
        'BAMBAN',
        'BOCAUE',
        'BONGABON',
        'BOTOLAN',
        'BULACAN',
        'BUSTOS',
        'CABANATUAN CITY',
        'CABANGAN',
        'CABIAO',
        'CALUMPIT',
        'CAMILING',
        'CANDABA',
        'CANDELARIA',
        'CAPAS',
        'CARRANGLAN',
        'CASIGURAN',
        'CASTILLEJOS',
        'CITY OF BALANGA (Capital)',
        'CITY OF GAPAN',
        'CITY OF MALOLOS (Capital)',
        'CITY OF MEYCAUAYAN',
        'CITY OF SAN FERNANDO (Capital)',
        'CITY OF SAN JOSE DEL MONTE',
        'CITY OF TARLAC (Capital)',
        'CONCEPCION',
        'CUYAPO',
        'DILASAG',
        'DINALUNGAN',
        'DINALUPIHAN',
        'DINGALAN',
        'DIPACULAO',
        'DOÑA REMEDIOS TRINIDAD',
        'FLORIDABLANCA',
        'GABALDON (BITULOK & SABANI)',
        'GENERAL MAMERTO NATIVIDAD',
        'GENERAL TINIO (PAPAYA)',
        'GERONA',
        'GUAGUA',
        'GUIGUINTO',
        'GUIMBA',
        'HAGONOY',
        'HERMOSA',
        'IBA (Capital)',
        'JAEN',
        'LA PAZ',
        'LAUR',
        'LICAB',
        'LIMAY',
        'LLANERA',
        'LUBAO',
        'LUPAO',
        'MABALACAT CITY',
        'MACABEBE',
        'MAGALANG',
        'MARIA AURORA',
        'MARILAO',
        'MARIVELES',
        'MASANTOL',
        'MASINLOC',
        'MAYANTOC',
        'MEXICO',
        'MINALIN',
        'MONCADA',
        'MORONG',
        'NAMPICUAN',
        'NORZAGARAY',
        'OBANDO',
        'OLONGAPO CITY',
        'ORANI',
        'ORION',
        'PALAUIG',
        'PALAYAN CITY (Capital)',
        'PANDI',
        'PANIQUI',
        'PANTABANGAN',
        'PAOMBONG',
        'PEÑARANDA',
        'PILAR',
        'PLARIDEL',
        'PORAC',
        'PULILAN',
        'PURA',
        'QUEZON',
        'RAMOS',
        'RIZAL',
        'SAMAL',
        'SAN ANTONIO',
        'SAN ANTONIO',
        'SAN CLEMENTE',
        'SAN FELIPE',
        'SAN ILDEFONSO',
        'SAN ISIDRO',
        'SAN JOSE',
        'SAN JOSE CITY',
        'SAN LEONARDO',
        'SAN LUIS',
        'SAN LUIS',
        'SAN MANUEL',
        'SAN MARCELINO',
        'SAN MIGUEL',
        'SAN NARCISO',
        'SAN RAFAEL',
        'SAN SIMON',
        'SANTA ANA',
        'SANTA CRUZ',
        'SANTA IGNACIA',
        'SANTA MARIA',
        'SANTA RITA',
        'SANTA ROSA',
        'SANTO DOMINGO',
        'SANTO TOMAS',
        'SASMUAN (Sexmoan)',
        'SCIENCE CITY OF MUÑOZ',
        'SUBIC',
        'TALAVERA',
        'TALUGTUG',
        'VICTORIA',
        'ZARAGOZA',
    ], 
    
    'REGION4A' : [
        'AGDANGAN',
        'AGONCILLO',
        'ALABAT',
        'ALAMINOS',
        'ALFONSO',
        'ALITAGTAG',
        'AMADEO',
        'ANGONO',
        'ATIMONAN',
        'BACOOR CITY',
        'BALAYAN',
        'BALETE',
        'BARAS',
        'BATANGAS CITY (Capital)',
        'BAUAN',
        'BAY',
        'BINANGONAN',
        'BUENAVISTA',
        'BURDEOS',
        'CABUYAO CITY',
        'CAINTA',
        'CALACA',
        'CALATAGAN',
        'CALAUAG',
        'CALAUAN',
        'CANDELARIA',
        'CARDONA',
        'CARMONA',
        'CATANAUAN',
        'CAVINTI',
        'CAVITE CITY',
        'CITY OF ANTIPOLO',
        'CITY OF BIÑAN',
        'CITY OF CALAMBA',
        'CITY OF DASMARIÑAS',
        'CITY OF SAN PEDRO',
        'CITY OF SANTA ROSA',
        'CITY OF TANAUAN',
        'CITY OF TAYABAS',
        'CUENCA',
        'DOLORES',
        'FAMY',
        'GEN. MARIANO ALVAREZ',
        'GENERAL EMILIO AGUINALDO',
        'GENERAL LUNA',
        'GENERAL NAKAR',
        'GENERAL TRIAS',
        'GUINAYANGAN',
        'GUMACA',
        'IBAAN',
        'IMUS CITY',
        'INDANG',
        'INFANTA',
        'JALA-JALA',
        'JOMALIG',
        'KALAYAAN',
        'KAWIT',
        'LAUREL',
        'LEMERY',
        'LIAN',
        'LILIW',
        'LIPA CITY',
        'LOBO',
        'LOPEZ',
        'LOS BAÑOS',
        'LUCBAN',
        'LUCENA CITY (Capital)',
        'LUISIANA',
        'LUMBAN',
        'MABINI',
        'MABITAC',
        'MACALELON',
        'MAGALLANES',
        'MAGDALENA',
        'MAJAYJAY',
        'MALVAR',
        'MARAGONDON',
        'MATAASNAKAHOY',
        'MAUBAN',
        'MENDEZ (MENDEZ-NUÑEZ)',
        'MORONG',
        'MULANAY',
        'NAGCARLAN',
        'NAIC',
        'NASUGBU',
        'NOVELETA',
        'PADRE BURGOS',
        'PADRE GARCIA',
        'PAETE',
        'PAGBILAO',
        'PAGSANJAN',
        'PAKIL',
        'PANGIL',
        'PANUKULAN',
        'PATNANUNGAN',
        'PEREZ',
        'PILA',
        'PILILLA',
        'PITOGO',
        'PLARIDEL',
        'POLILLO',
        'QUEZON',
        'REAL',
        'RIZAL',
        'RODRIGUEZ (MONTALBAN)',
        'ROSARIO',
        'ROSARIO',
        'SAMPALOC',
        'SAN ANDRES',
        'SAN ANTONIO',
        'SAN FRANCISCO (AURORA)',
        'SAN JOSE',
        'SAN JUAN',
        'SAN LUIS',
        'SAN MATEO',
        'SAN NARCISO',
        'SAN NICOLAS',
        'SAN PABLO CITY',
        'SAN PASCUAL',
        'SANTA CRUZ (Capital)',
        'SANTA MARIA',
        'SANTA TERESITA',
        'SANTO TOMAS',
        'SARIAYA',
        'SILANG',
        'SINILOAN',
        'TAAL',
        'TAGAYTAY CITY',
        'TAGKAWAYAN',
        'TALISAY',
        'TANAY',
        'TANZA',
        'TAYSAN',
        'TAYTAY',
        'TERESA',
        'TERNATE',
        'TIAONG',
        'TINGLOY',
        'TRECE MARTIRES CITY (Capital)',
        'TUY',
        'UNISAN',
        'VICTORIA',
    ],
    
    'REGION4B' : [
        'ABORLAN',
        'ABRA DE ILOG',
        'AGUTAYA',
        'ALCANTARA',
        'ARACELI',
        'BACO',
        'BALABAC',
        'BANSUD',
        'BANTON',
        'BATARAZA',
        'BOAC (Capital)',
        'BONGABONG',
        "BROOKE'S POINT",
        'BUENAVISTA',
        'BULALACAO (SAN PEDRO)',
        'BUSUANGA',
        'CAGAYANCILLO',
        'CAJIDIOCAN',
        'CALATRAVA',
        'CALINTAAN',
        'CITY OF CALAPAN (Capital)',
        'CONCEPCION',
        'CORCUERA',
        'CORON',
        'CULION',
        'CUYO',
        'DUMARAN',
        'EL NIDO (BACUIT)',
        'FERROL',
        'GASAN',
        'GLORIA',
        'KALAYAAN',
        'LINAPACAN',
        'LOOC',
        'LOOC',
        'LUBANG',
        'MAGDIWANG',
        'MAGSAYSAY',
        'MAGSAYSAY',
        'MAMBURAO (Capital)',
        'MANSALAY',
        'MOGPOG',
        'NARRA',
        'NAUJAN',
        'ODIONGAN',
        'PALUAN',
        'PINAMALAYAN',
        'POLA',
        'PUERTO GALERA',
        'PUERTO PRINCESA CITY (Capital)',
        'QUEZON',
        'RIZAL',
        'RIZAL (MARCOS)',
        'ROMBLON (Capital)',
        'ROXAS',
        'ROXAS',
        'SABLAYAN',
        'SAN AGUSTIN',
        'SAN ANDRES',
        'SAN FERNANDO',
        'SAN JOSE',
        'SAN JOSE',
        'SAN TEODORO',
        'SAN VICENTE',
        'SANTA CRUZ',
        'SANTA CRUZ',
        'SANTA FE',
        'SANTA MARIA (IMELDA)',
        'SOCORRO',
        'SOFRONIO ESPAÑOLA',
        'TAYTAY',
        'TORRIJOS',
        'VICTORIA',
    ],
    
    'REGION5' : [
        'AROROY',
        'BAAO',
        'BACACAY',
        'BAGAMANOC',
        'BALATAN',
        'BALENO',
        'BALUD',
        'BARAS',
        'BARCELONA',
        'BASUD',
        'BATO',
        'BATO',
        'BATUAN',
        'BOMBON',
        'BUHI',
        'BULA',
        'BULAN',
        'BULUSAN',
        'CABUSAO',
        'CALABANGA',
        'CAMALIG',
        'CAMALIGAN',
        'CANAMAN',
        'CAPALONGA',
        'CARAMOAN',
        'CARAMORAN',
        'CASIGURAN',
        'CASTILLA',
        'CATAINGAN',
        'CAWAYAN',
        'CITY OF LIGAO',
        'CITY OF MASBATE (Capital)',
        'CITY OF SORSOGON (Capital)',
        'CITY OF TABACO',
        'CLAVERIA',
        'DAET (Capital)',
        'DARAGA (LOCSIN)',
        'DEL GALLEGO',
        'DIMASALANG',
        'DONSOL',
        'ESPERANZA',
        'GAINZA',
        'GARCHITORENA',
        'GIGMOTO',
        'GOA',
        'GUBAT',
        'GUINOBATAN',
        'IRIGA CITY',
        'IROSIN',
        'JOSE PANGANIBAN',
        'JOVELLAR',
        'JUBAN',
        'LABO',
        'LAGONOY',
        'LEGAZPI CITY (Capital)',
        'LIBMANAN',
        'LIBON',
        'LUPI',
        'MAGALLANES',
        'MAGARAO',
        'MALILIPOT',
        'MALINAO',
        'MANDAON',
        'MANITO',
        'MATNOG',
        'MERCEDES',
        'MILAGROS',
        'MILAOR',
        'MINALABAC',
        'MOBO',
        'MONREAL',
        'NABUA',
        'NAGA CITY',
        'OAS',
        'OCAMPO',
        'PALANAS',
        'PAMPLONA',
        'PANDAN',
        'PANGANIBAN (PAYO)',
        'PARACALE',
        'PASACAO',
        'PILAR',
        'PILI (Capital)',
        'PIO DURAN',
        'PIO V. CORPUZ (LIMBUHAN)',
        'PLACER',
        'POLANGUI',
        'PRESENTACION (PARUBCAN)',
        'PRIETO DIAZ',
        'RAGAY',
        'RAPU-RAPU',
        'SAGÑAY',
        'SAN ANDRES (CALOLBON)',
        'SAN FERNANDO',
        'SAN FERNANDO',
        'SAN JACINTO',
        'SAN JOSE',
        'SAN LORENZO RUIZ (IMELDA)',
        'SAN MIGUEL',
        'SAN PASCUAL',
        'SAN VICENTE',
        'SANTA ELENA',
        'SANTA MAGDALENA',
        'SANTO DOMINGO (LIBOG)',
        'SIPOCOT',
        'SIRUMA',
        'TALISAY',
        'TIGAON',
        'TINAMBAC',
        'TIWI',
        'USON',
        'VIGA',
        'VINZONS',
        'VIRAC (Capital)',
    ],
    
    'REGION6' : [
        'AJUY',
        'ALIMODIAN',
        'ALTAVAS',
        'ANILAO',
        'ANINI-Y',
        'BACOLOD CITY (Capital)',
        'BADIANGAN',
        'BAGO CITY',
        'BALASAN',
        'BALETE',
        'BANATE',
        'BANGA',
        'BARBAZA',
        'BAROTAC NUEVO',
        'BAROTAC VIEJO',
        'BATAD',
        'BATAN',
        'BELISON',
        'BINALBAGAN',
        'BINGAWAN',
        'BUENAVISTA',
        'BUGASONG',
        'BURUANGA',
        'CABATUAN',
        'CADIZ CITY',
        'CALATRAVA',
        'CALINOG',
        'CALUYA',
        'CANDONI',
        'CARLES',
        'CAUAYAN',
        'CITY OF ESCALANTE',
        'CITY OF HIMAMAYLAN',
        'CITY OF KABANKALAN',
        'CITY OF PASSI',
        'CITY OF SIPALAY',
        'CITY OF TALISAY',
        'CITY OF VICTORIAS',
        'CONCEPCION',
        'CUARTERO',
        'CULASI',
        'DAO',
        'DINGLE',
        'DUEÑAS',
        'DUMALAG',
        'DUMANGAS',
        'DUMARAO',
        'ENRIQUE B. MAGALONA (SARAVIA)',
        'ESTANCIA',
        'GUIMBAL',
        'HAMTIC',
        'HINIGARAN',
        'HINOBA-AN (ASIA)',
        'IBAJAY',
        'IGBARAS',
        'ILOG',
        'ILOILO CITY (Capital)',
        'ISABELA',
        'IVISAN',
        'JAMINDAN',
        'JANIUAY',
        'JORDAN (Capital)',
        'KALIBO (Capital)',
        'LA CARLOTA CITY',
        'LA CASTELLANA',
        'LAMBUNAO',
        'LAUA-AN',
        'LEGANES',
        'LEMERY',
        'LEON',
        'LEZO',
        'LIBACAO',
        'LIBERTAD',
        'MA-AYON',
        'MAASIN',
        'MADALAG',
        'MAKATO',
        'MALAY',
        'MALINAO',
        'MAMBUSAO',
        'MANAPLA',
        'MIAGAO',
        'MINA',
        'MOISES PADILLA (MAGALLON)',
        'MURCIA',
        'NABAS',
        'NEW LUCENA',
        'NEW WASHINGTON',
        'NUEVA VALENCIA',
        'NUMANCIA',
        'OTON',
        'PANAY',
        'PANDAN',
        'PANITAN',
        'PATNONGON',
        'PAVIA',
        'PILAR',
        'PONTEVEDRA',
        'PONTEVEDRA',
        'POTOTAN',
        'PRESIDENT ROXAS',
        'PULUPANDAN',
        'ROXAS CITY (Capital)',
        'SAGAY CITY',
        'SALVADOR BENEDICTO',
        'SAN CARLOS CITY',
        'SAN DIONISIO',
        'SAN ENRIQUE',
        'SAN ENRIQUE',
        'SAN JOAQUIN',
        'SAN JOSE (Capital)',
        'SAN LORENZO',
        'SAN MIGUEL',
        'SAN RAFAEL',
        'SAN REMIGIO',
        'SANTA BARBARA',
        'SAPI-AN',
        'SARA',
        'SEBASTE',
        'SIBALOM',
        'SIBUNAG',
        'SIGMA',
        'SILAY CITY',
        'TANGALAN',
        'TAPAZ',
        'TIBIAO',
        'TIGBAUAN',
        'TOBIAS FORNIER (DAO)',
        'TOBOSO',
        'TUBUNGAN',
        'VALDERRAMA',
        'VALLADOLID',
        'ZARRAGA',
    ],

    'REGION7' : [
        'ALBURQUERQUE',
        'ALCANTARA',
        'ALCOY',
        'ALEGRIA',
        'ALICIA',
        'ALOGUINSAN',
        'AMLAN (AYUQUITAN)',
        'ANDA',
        'ANTEQUERA',
        'ARGAO',
        'ASTURIAS',
        'AYUNGON',
        'BACLAYON',
        'BACONG',
        'BADIAN',
        'BAIS CITY',
        'BALAMBAN',
        'BALILIHAN',
        'BANTAYAN',
        'BARILI',
        'BASAY',
        'BATUAN',
        'BIEN UNIDO',
        'BILAR',
        'BINDOY (PAYABON)',
        'BOLJOON',
        'BORBON',
        'BUENAVISTA',
        'CALAPE',
        'CANDIJAY',
        'CANLAON CITY',
        'CARMEN',
        'CARMEN',
        'CATIGBIAN',
        'CATMON',
        'CEBU CITY (Capital)',
        'CITY OF BAYAWAN (TULONG)',
        'CITY OF BOGO',
        'CITY OF CARCAR',
        'CITY OF GUIHULNGAN',
        'CITY OF NAGA',
        'CITY OF TALISAY',
        'CITY OF TANJAY',
        'CLARIN',
        'COMPOSTELA',
        'CONSOLACION',
        'CORDOVA',
        'CORELLA',
        'CORTES',
        'DAANBANTAYAN',
        'DAGOHOY',
        'DALAGUETE',
        'DANAO',
        'DANAO CITY',
        'DAUIN',
        'DAUIS',
        'DIMIAO',
        'DUERO',
        'DUMAGUETE CITY (Capital)',
        'DUMANJUG',
        'ENRIQUE VILLANUEVA',
        'GARCIA HERNANDEZ',
        'GINATILAN',
        'GUINDULMAN',
        'INABANGA',
        'JAGNA',
        'JETAFE',
        'JIMALALUD',
        'LA LIBERTAD',
        'LAPU-LAPU CITY (OPON)',
        'LARENA',
        'LAZI',
        'LILA',
        'LILOAN',
        'LOAY',
        'LOBOC',
        'LOON',
        'MABINAY',
        'MABINI',
        'MADRIDEJOS',
        'MALABUYOC',
        'MANDAUE CITY',
        'MANJUYOD',
        'MARIA',
        'MARIBOJOC',
        'MEDELLIN',
        'MINGLANILLA',
        'MOALBOAL',
        'OSLOB',
        'PAMPLONA',
        'PANGLAO',
        'PILAR',
        'PILAR',
        'PINAMUNGAHAN',
        'PORO',
        'PRES. CARLOS P. GARCIA (PITOGO)',
        'RONDA',
        'SAGBAYAN (BORJA)',
        'SAMBOAN',
        'SAN FERNANDO',
        'SAN FRANCISCO',
        'SAN ISIDRO',
        'SAN JOSE',
        'SAN JUAN',
        'SAN MIGUEL',
        'SAN REMIGIO',
        'SANTA CATALINA',
        'SANTA FE',
        'SANTANDER',
        'SEVILLA',
        'SIATON',
        'SIBONGA',
        'SIBULAN',
        'SIERRA BULLONES',
        'SIKATUNA',
        'SIQUIJOR (Capital)',
        'SOGOD',
        'TABOGON',
        'TABUELAN',
        'TAGBILARAN CITY (Capital)',
        'TALIBON',
        'TAYASAN',
        'TOLEDO CITY',
        'TRINIDAD',
        'TUBIGON',
        'TUBURAN',
        'TUDELA',
        'UBAY',
        'VALENCIA',
        'VALENCIA (LUZURRIAGA)',
        'VALLEHERMOSO',
        'ZAMBOANGUITA',
    ],
    
    'REGION8' : [
        'ABUYOG',
        'ALANGALANG',
        'ALBUERA',
        'ALLEN',
        'ALMAGRO',
        'ALMERIA',
        'ANAHAWAN',
        'ARTECHE',
        'BABATNGON',
        'BALANGIGA',
        'BALANGKAYAN',
        'BARUGO',
        'BASEY',
        'BATO',
        'BILIRAN',
        'BIRI',
        'BOBON',
        'BONTOC',
        'BURAUEN',
        'CABUCGAYAN',
        'CAIBIRAN',
        'CALBAYOG CITY',
        'CALBIGA',
        'CALUBIAN',
        'CAN-AVID',
        'CAPOOCAN',
        'CAPUL',
        'CARIGARA',
        'CATARMAN (Capital)',
        'CATUBIG',
        'CITY OF BAYBAY',
        'CITY OF BORONGAN (Capital)',
        'CITY OF CATBALOGAN (Capital)',
        'CITY OF MAASIN (Capital)',
        'CULABA',
        'DAGAMI',
        'DARAM',
        'DOLORES',
        'DULAG',
        'GAMAY',
        'GANDARA',
        'GENERAL MACARTHUR',
        'GIPORLOS',
        'GUIUAN',
        'HERNANI',
        'HILONGOS',
        'HINABANGAN',
        'HINDANG',
        'HINUNANGAN',
        'HINUNDAYAN',
        'INOPACAN',
        'ISABEL',
        'JARO',
        'JAVIER (BUGHO)',
        'JIABONG',
        'JIPAPAD',
        'JULITA',
        'KANANGA',
        'KAWAYAN',
        'LA PAZ',
        'LAOANG',
        'LAPINIG',
        'LAS NAVAS',
        'LAVEZARES',
        'LAWAAN',
        'LEYTE',
        'LIBAGON',
        'LILOAN',
        'LIMASAWA',
        'LLORENTE',
        'LOPE DE VEGA',
        'MACARTHUR',
        'MACROHON',
        'MAHAPLAG',
        'MALITBOG',
        'MAPANAS',
        'MARABUT',
        'MARIPIPI',
        'MASLOG',
        'MATAG-OB',
        'MATALOM',
        'MATUGUINAO',
        'MAYDOLONG',
        'MAYORGA',
        'MERCEDES',
        'MERIDA',
        'MONDRAGON',
        'MOTIONG',
        'NAVAL (Capital)',
        'ORAS',
        'ORMOC CITY',
        'PADRE BURGOS',
        'PAGSANGHAN',
        'PALAPAG',
        'PALO',
        'PALOMPON',
        'PAMBUJAN',
        'PARANAS (WRIGHT)',
        'PASTRANA',
        'PINABACDAO',
        'PINTUYAN',
        'QUINAPONDAN',
        'ROSARIO',
        'SAINT BERNARD',
        'SALCEDO',
        'SAN ANTONIO',
        'SAN FRANCISCO',
        'SAN ISIDRO',
        'SAN ISIDRO',
        'SAN JORGE',
        'SAN JOSE',
        'SAN JOSE DE BUAN',
        'SAN JUAN (CABALIAN)',
        'SAN JULIAN',
        'SAN MIGUEL',
        'SAN POLICARPO',
        'SAN RICARDO',
        'SAN ROQUE',
        'SAN SEBASTIAN',
        'SAN VICENTE',
        'SANTA FE',
        'SANTA MARGARITA',
        'SANTA RITA',
        'SANTO NIÑO',
        'SILAGO',
        'SILVINO LOBOS',
        'SOGOD',
        'SULAT',
        'TABANGO',
        'TABONTABON',
        'TACLOBAN CITY (Capital)',
        'TAFT',
        'TAGAPUL-AN',
        'TALALORA',
        'TANAUAN',
        'TARANGNAN',
        'TOLOSA',
        'TOMAS OPPUS',
        'TUNGA',
        'VICTORIA',
        'VILLABA',
        'VILLAREAL',
        'ZUMARRAGA',
    ],
    
    'REGION9' : [
        'ALICIA',
        'AURORA',
        'BACUNGAN (Leon T. Postigo)',
        'BALIGUIAN',
        'BAYOG',
        'BUUG',
        'CITY OF ISABELA',
        'DAPITAN CITY',
        'DIMATALING',
        'DINAS',
        'DIPLAHAN',
        'DIPOLOG CITY (Capital)',
        'DUMALINAO',
        'DUMINGAG',
        'GODOD',
        'GUIPOS',
        'GUTALAC',
        'IMELDA',
        'IPIL (Capital)',
        'JOSE DALMAN (PONOT)',
        'JOSEFINA',
        'KABASALAN',
        'KALAWIT',
        'KATIPUNAN',
        'KUMALARANG',
        'LA LIBERTAD',
        'LABANGAN',
        'LABASON',
        'LAKEWOOD',
        'LAPUYAN',
        'LILOY',
        'MABUHAY',
        'MAHAYAG',
        'MALANGAS',
        'MANUKAN',
        'MARGOSATUBIG',
        'MIDSALIP',
        'MOLAVE',
        'MUTIA',
        'NAGA',
        'OLUTANGA',
        'PAGADIAN CITY (Capital)',
        'PAYAO',
        'PIÑAN (NEW PIÑAN)',
        'PITOGO',
        'POLANCO',
        'PRES. MANUEL A. ROXAS',
        'RAMON MAGSAYSAY (LIARGO)',
        'RIZAL',
        'ROSELLER LIM',
        'SALUG',
        'SAN MIGUEL',
        'SAN PABLO',
        'SERGIO OSMEÑA SR.',
        'SIAY',
        'SIAYAN',
        'SIBUCO',
        'SIBUTAD',
        'SINDANGAN',
        'SIOCON',
        'SIRAWAI',
        'SOMINOT (DON MARIANO MARCOS)',
        'TABINA',
        'TALUSAN',
        'TAMBULIG',
        'TAMPILISAN',
        'TIGBAO',
        'TITAY',
        'TUKURAN',
        'TUNGAWAN',
        'VINCENZO A. SAGUN',
        'ZAMBOANGA CITY',
    ],
    
    'REGION10' : [
        'ALORAN',
        'ALUBIJID',
        'BACOLOD',
        'BALIANGAO',
        'BALINGASAG',
        'BALINGOAN',
        'BALOI',
        'BAROY',
        'BAUNGON',
        'BINUANGAN',
        'BONIFACIO',
        'CABANGLASAN',
        'CAGAYAN DE ORO CITY (Capital)',
        'CALAMBA',
        'CATARMAN',
        'CITY OF EL SALVADOR',
        'CITY OF MALAYBALAY (Capital)',
        'CITY OF VALENCIA',
        'CLARIN',
        'CLAVERIA',
        'CONCEPCION',
        'DAMULOG',
        'DANGCAGAN',
        'DON CARLOS',
        'DON VICTORIANO CHIONGBIAN (DON MARIANO MARCOS)',
        'GINGOOG CITY',
        'GITAGUM',
        'GUINSILIBAN',
        'ILIGAN CITY',
        'IMPASUG-ONG',
        'INITAO',
        'JASAAN',
        'JIMENEZ',
        'KADINGILAN',
        'KALILANGAN',
        'KAPATAGAN',
        'KAUSWAGAN',
        'KIBAWE',
        'KINOGUITAN',
        'KITAOTAO',
        'KOLAMBUGAN',
        'LAGONGLONG',
        'LAGUINDINGAN',
        'LALA',
        'LANTAPAN',
        'LIBERTAD',
        'LIBONA',
        'LINAMON',
        'LOPEZ JAENA',
        'LUGAIT',
        'MAGSAYSAY',
        'MAGSAYSAY (LINUGOS)',
        'MAHINOG',
        'MAIGO',
        'MALITBOG',
        'MAMBAJAO (Capital)',
        'MANOLO FORTICH',
        'MANTICAO',
        'MARAMAG',
        'MATUNGAO',
        'MEDINA',
        'MUNAI',
        'NAAWAN',
        'NUNUNGAN',
        'OPOL',
        'OROQUIETA CITY (Capital)',
        'OZAMIS CITY',
        'PANAON',
        'PANGANTUCAN',
        'PANTAO RAGAT',
        'PANTAR',
        'PLARIDEL',
        'POONA PIAGAPO',
        'QUEZON',
        'SAGAY',
        'SALAY',
        'SALVADOR',
        'SAN FERNANDO',
        'SAPAD',
        'SAPANG DALAGA',
        'SINACABAN',
        'SUGBONGCOGON',
        'SULTAN NAGA DIMAPORO (KAROMATAN)',
        'SUMILAO',
        'TAGOLOAN',
        'TAGOLOAN',
        'TALAKAG',
        'TALISAYAN',
        'TANGCAL',
        'TANGUB CITY',
        'TUBOD (Capital)',
        'TUDELA',
        'VILLANUEVA',
    ],
    
    'REGION11' : [
        'ASUNCION (SAUG)',
        'BAGANGA',
        'BANAYBANAY',
        'BANSALAN',
        'BOSTON',
        'BRAULIO E. DUJALI',
        'CARAGA',
        'CARMEN',
        'CATEEL',
        'CITY OF DIGOS (Capital)',
        'CITY OF MATI (Capital)',
        'CITY OF PANABO',
        'CITY OF TAGUM (Capital)',
        'COMPOSTELA',
        'DAVAO CITY',
        'DON MARCELINO',
        'GOVERNOR GENEROSO',
        'HAGONOY',
        'ISLAND GARDEN CITY OF SAMAL',
        'JOSE ABAD SANTOS (TRINIDAD)',
        'KAPALONG',
        'KIBLAWAN',
        'LAAK (SAN VICENTE)',
        'LUPON',
        'MABINI (DOÑA ALICIA)',
        'MACO',
        'MAGSAYSAY',
        'MALALAG',
        'MALITA',
        'MANAY',
        'MARAGUSAN (SAN MARIANO)',
        'MATANAO',
        'MAWAB',
        'MONKAYO',
        'MONTEVISTA',
        'NABUNTURAN (Capital)',
        'NEW BATAAN',
        'NEW CORELLA',
        'PADADA',
        'PANTUKAN',
        'SAN ISIDRO',
        'SAN ISIDRO',
        'SANTA CRUZ',
        'SANTA MARIA',
        'SANTO TOMAS',
        'SARANGANI',
        'SULOP',
        'TALAINGOD',
        'TARRAGONA',
    ],
    
    'REGION12' : [
        'ALABEL (Capital)',
        'ALAMADA',
        'ALEOSAN',
        'ANTIPAS',
        'ARAKAN',
        'BAGUMBAYAN',
        'BANGA',
        'BANISILAN',
        'CARMEN',
        'CITY OF KIDAPAWAN (Capital)',
        'CITY OF KORONADAL (Capital)',
        'CITY OF TACURONG',
        'COLUMBIO',
        'COTABATO CITY',
        'ESPERANZA',
        'GENERAL SANTOS CITY (DADIANGAS)',
        'GLAN',
        'ISULAN (Capital)',
        'KABACAN',
        'KALAMANSIG',
        'KIAMBA',
        'LAKE SEBU',
        'LAMBAYONG (MARIANO MARCOS)',
        'LEBAK',
        'LIBUNGAN',
        'LUTAYAN',
        "M'LANG",
        'MAASIM',
        'MAGPET',
        'MAITUM',
        'MAKILALA',
        'MALAPATAN',
        'MALUNGON',
        'MATALAM',
        'MIDSAYAP',
        'NORALA',
        'PALIMBANG',
        'PIGKAWAYAN',
        'PIKIT',
        'POLOMOLOK',
        'PRESIDENT QUIRINO',
        'PRESIDENT ROXAS',
        'SANTO NIÑO',
        'SEN. NINOY AQUINO',
        'SURALLAH',
        "T'BOLI",
        'TAMPAKAN',
        'TANTANGAN',
        'TULUNAN',
        'TUPI',
    ],

    'NCR' : [
        'BINONDO',
        'CALOOCAN CITY',
        'CITY OF LAS PIÑAS',
        'CITY OF MAKATI',
        'CITY OF MALABON',
        'CITY OF MANDALUYONG',
        'CITY OF MARIKINA',
        'CITY OF MUNTINLUPA',
        'CITY OF NAVOTAS',
        'CITY OF PARAÑAQUE',
        'CITY OF PASIG',
        'CITY OF SAN JUAN',
        'CITY OF VALENZUELA',
        'ERMITA',
        'INTRAMUROS',
        'MALATE',
        'PACO',
        'PANDACAN',
        'PASAY CITY',
        'PATEROS',
        'PORT AREA',
        'QUEZON CITY',
        'QUIAPO',
        'SAMPALOC',
        'SAN MIGUEL',
        'SAN NICOLAS',
        'SANTA ANA',
        'SANTA CRUZ',
        'TAGUIG CITY',
        'TONDO I / II',
    ],
    
    'CAR' : [
        'AGUINALDO',
        'ALFONSO LISTA (POTIA)',
        'ASIPULO',
        'ATOK',
        'BAGUIO CITY',
        'BAKUN',
        'BALBALAN',
        'BANAUE',
        'BANGUED (Capital)',
        'BARLIG',
        'BAUKO',
        'BESAO',
        'BOKOD',
        'BOLINEY',
        'BONTOC (Capital)',
        'BUCAY',
        'BUCLOC',
        'BUGUIAS',
        'CALANASAN (BAYAG)',
        'CITY OF TABUK (Capital)',
        'CONNER',
        'DAGUIOMAN',
        'DANGLAS',
        'DOLORES',
        'FLORA',
        'HINGYON',
        'HUNGDUAN',
        'ITOGON',
        'KABAYAN',
        'KABUGAO (Capital)',
        'KAPANGAN',
        'KIANGAN',
        'KIBUNGAN',
        'LA PAZ',
        'LA TRINIDAD (Capital)',
        'LACUB',
        'LAGANGILANG',
        'LAGAWE (Capital)',
        'LAGAYAN',
        'LAMUT',
        'LANGIDEN',
        'LICUAN-BAAY (LICUAN)',
        'LUBA',
        'LUBUAGAN',
        'LUNA',
        'MALIBCONG',
        'MANABO',
        'MANKAYAN',
        'MAYOYAO',
        'NATONIN',
        'PARACELIS',
        'PASIL',
        'PEÑARRUBIA',
        'PIDIGAN',
        'PILAR',
        'PINUKPUK',
        'PUDTOL',
        'RIZAL (LIWAN)',
        'SABANGAN',
        'SABLAN',
        'SADANGA',
        'SAGADA',
        'SALLAPADAN',
        'SAN ISIDRO',
        'SAN JUAN',
        'SAN QUINTIN',
        'SANTA MARCELA',
        'TADIAN',
        'TANUDAN',
        'TAYUM',
        'TINEG',
        'TINGLAYAN',
        'TINOC',
        'TUBA',
        'TUBLAY',
        'TUBO',
        'VILLAVICIOSA',
    ],
    
    'ARMM' : [
        'AKBAR',
        'AL-BARKA',
        'AMPATUAN',
        'BACOLOD-KALAWI (BACOLOD GRANDE)',
        'BALABAGAN',
        'BALINDONG (WATU)',
        'BARIRA',
        'BAYANG',
        'BINIDAYAN',
        'BONGAO (Capital)',
        'BUADIPOSO-BUNTONG',
        'BUBONG',
        'BULDON',
        'BULUAN',
        'BUMBARAN',
        'BUTIG',
        'CALANOGAS',
        'CITY OF LAMITAN',
        'DATU ABDULLAH SANGKI',
        'DATU ANGGAL MIDTIMBANG',
        'DATU BLAH T. SINSUAT',
        'DATU HOFFER AMPATUAN',
        'DATU ODIN SINSUAT (DINAIG)',
        'DATU PAGLAS',
        'DATU PIANG',
        'DATU SALIBO',
        'DATU SAUDI-AMPATUAN',
        'DATU UNSAY',
        'DITSAAN-RAMAIN',
        'GANASSI',
        'GEN. S. K. PENDATUN',
        'GUINDULUNGAN',
        'HADJI MOHAMMAD AJUL',
        'HADJI MUHTAMAD',
        'HADJI PANGLIMA TAHIL (MARUNGGAS)',
        'INDANAN',
        'JOLO (Capital)',
        'KABUNTALAN (TUMBAO)',
        'KALINGALAN CALUANG',
        'KAPAI',
        'KAPATAGAN',
        'LANGUYAN',
        'LANTAWAN',
        'LUGUS',
        'LUMBA-BAYABAO (MAGUING)',
        'LUMBACA-UNAYAN',
        'LUMBATAN',
        'LUMBAYANAGUE',
        'LUUK',
        'MADALUM',
        'MADAMBA',
        'MAGUING',
        'MAIMBUNG',
        'MALABANG',
        'MALUSO',
        'MAMASAPANO',
        'MANGUDADATU',
        'MAPUN (CAGAYAN DE TAWI-TAWI)',
        'MARANTAO',
        'MARAWI CITY (Capital)',
        'MAROGONG',
        'MASIU',
        'MATANOG',
        'MULONDO',
        'NORTHERN KABUNTALAN',
        'OLD PANAMAO',
        'OMAR',
        'PAGAGAWAN',
        'PAGALUNGAN',
        'PAGAYAWAN (TATARIKAN)',
        'PAGLAT',
        'PANDAG',
        'PANDAMI',
        'PANGLIMA ESTINO (NEW PANAMAO)',
        'PANGLIMA SUGALA (BALIMBING)',
        'PANGUTARAN',
        'PARANG',
        'PARANG',
        'PATA',
        'PATIKUL',
        'PIAGAPO',
        'PICONG (SULTAN GUMANDER)',
        'POONA BAYABAO (GATA)',
        'PUALAS',
        'RAJAH BUAYAN',
        'SAGUIARAN',
        'SAPA-SAPA',
        'SHARIFF AGUAK (MAGANOY) (Capital)',
        'SHARIFF SAYDONA MUSTAPHA',
        'SIASI',
        'SIBUTU',
        'SIMUNUL',
        'SITANGKAI',
        'SOUTH UBIAN',
        'SOUTH UPI',
        'SULTAN DUMALONDONG',
        'SULTAN KUDARAT (NULING)',
        'SULTAN MASTURA',
        'SULTAN SA BARONGIS (LAMBAYONG)',
        'SUMISIP',
        'TABUAN-LASA',
        'TAGOLOAN II',
        'TALAYAN',
        'TALIPAO',
        'TALITAY',
        'TAMPARAN',
        'TANDUBAS',
        'TAPUL',
        'TARAKA',
        'TIPO-TIPO',
        'TONGKIL',
        'TUBARAN',
        'TUBURAN',
        'TUGAYA',
        'TURTLE ISLANDS',
        'UNGKAYA PUKAN',
        'UPI',
        'WAO',
    ],
    
    'REGION13' : [
        'ALEGRIA',
        'BACUAG',
        'BAROBO',
        'BASILISA (RIZAL)',
        'BAYABAS',
        'BUENAVISTA',
        'BUNAWAN',
        'BURGOS',
        'BUTUAN CITY (Capital)',
        'CAGDIANAO',
        'CAGWAIT',
        'CANTILAN',
        'CARMEN',
        'CARMEN',
        'CARRASCAL',
        'CITY OF BAYUGAN',
        'CITY OF BISLIG',
        'CITY OF CABADBARAN',
        'CITY OF TANDAG (Capital)',
        'CLAVER',
        'CORTES',
        'DAPA',
        'DEL CARMEN',
        'DINAGAT',
        'ESPERANZA',
        'GENERAL LUNA',
        'GIGAQUIT',
        'HINATUAN',
        'JABONGA',
        'KITCHARAO',
        'LA PAZ',
        'LANUZA',
        'LAS NIEVES',
        'LIANGA',
        'LIBJO (ALBOR)',
        'LINGIG',
        'LORETO',
        'LORETO',
        'MADRID',
        'MAGALLANES',
        'MAINIT',
        'MALIMONO',
        'MARIHATAG',
        'NASIPIT',
        'PILAR',
        'PLACER',
        'PROSPERIDAD (Capital)',
        'REMEDIOS T. ROMUALDEZ',
        'ROSARIO',
        'SAN AGUSTIN',
        'SAN BENITO',
        'SAN FRANCISCO',
        'SAN FRANCISCO (ANAO-AON)',
        'SAN ISIDRO',
        'SAN JOSE (Capital)',
        'SAN LUIS',
        'SAN MIGUEL',
        'SANTA JOSEFA',
        'SANTA MONICA (SAPAO)',
        'SANTIAGO',
        'SIBAGAT',
        'SISON',
        'SOCORRO',
        'SURIGAO CITY (Capital)',
        'TAGANA-AN',
        'TAGBINA',
        'TAGO',
        'TALACOGON',
        'TRENTO',
        'TUBAJON',
        'TUBAY',
        'TUBOD',
        'VERUELA',
    ]    
}



GENDER = [
    'Male',
    'Female',
    "I\u2019d rather not say",
]